spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aqua_olsberg}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:4qhq8LrEBfYcaRHxhdb9zURb2rf8e7Ud4qhq8LrEBfYcaRHxhdb9zURb2rf8e7Ud}
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:olsberg2026}